
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class BackgroundDefine : Luban.BeanBase
{
    public BackgroundDefine(ByteBuf _buf) 
    {
        BackgroundId = _buf.ReadString();
        PackageId = _buf.ReadString();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); SkillProficiencies = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); SkillProficiencies.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ToolProficiencies = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ToolProficiencies.Add(_e0);}}
        {int n0 = _buf.ReadSize(); LanguageIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); LanguageIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); FeatureIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); FeatureIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); EquipmentGrantIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); EquipmentGrantIds.Add(_e0);}}
        Description = _buf.ReadString();
    }

    public static BackgroundDefine DeserializeBackgroundDefine(ByteBuf _buf)
    {
        return new dnd.BackgroundDefine(_buf);
    }

    /// <summary>
    /// 背景唯一ID。
    /// </summary>
    public readonly string BackgroundId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> SkillProficiencies;
    /// <summary>
    /// 工具熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ToolProficiencies;
    /// <summary>
    /// 语言列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> LanguageIds;
    /// <summary>
    /// 背景特性列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeatureIds;
    /// <summary>
    /// 装备授予。第一版可留空。
    /// </summary>
    public readonly System.Collections.Generic.List<string> EquipmentGrantIds;
    /// <summary>
    /// 用户录入说明。
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 991967997;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "backgroundId:" + BackgroundId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "skillProficiencies:" + Luban.StringUtil.CollectionToString(SkillProficiencies) + ","
        + "toolProficiencies:" + Luban.StringUtil.CollectionToString(ToolProficiencies) + ","
        + "languageIds:" + Luban.StringUtil.CollectionToString(LanguageIds) + ","
        + "featureIds:" + Luban.StringUtil.CollectionToString(FeatureIds) + ","
        + "equipmentGrantIds:" + Luban.StringUtil.CollectionToString(EquipmentGrantIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

