
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class ChoiceOption : Luban.BeanBase
{
    public ChoiceOption(ByteBuf _buf) 
    {
        ChoiceGroupId = _buf.ReadString();
        OptionId = _buf.ReadString();
        Name = _buf.ReadString();
        {int n0 = _buf.ReadSize(); GrantFeatureIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); GrantFeatureIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); GrantEffectIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); GrantEffectIds.Add(_e0);}}
        Description = _buf.ReadString();
    }

    public static ChoiceOption DeserializeChoiceOption(ByteBuf _buf)
    {
        return new dnd.ChoiceOption(_buf);
    }

    /// <summary>
    /// 所属选择组ID。
    /// </summary>
    public readonly string ChoiceGroupId;
    /// <summary>
    /// 选项唯一ID。
    /// </summary>
    public readonly string OptionId;
    /// <summary>
    /// 选项显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 选择后授予的特性ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> GrantFeatureIds;
    /// <summary>
    /// 选择后直接授予的效果ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> GrantEffectIds;
    /// <summary>
    /// 用户录入说明。
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -1545999894;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "choiceGroupId:" + ChoiceGroupId + ","
        + "optionId:" + OptionId + ","
        + "name:" + Name + ","
        + "grantFeatureIds:" + Luban.StringUtil.CollectionToString(GrantFeatureIds) + ","
        + "grantEffectIds:" + Luban.StringUtil.CollectionToString(GrantEffectIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

