
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class ClassDefine : Luban.BeanBase
{
    public ClassDefine(ByteBuf _buf) 
    {
        ClassId = _buf.ReadString();
        PackageId = _buf.ReadString();
        Name = _buf.ReadString();
        HitDie = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); PrimaryAbilityIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); PrimaryAbilityIds.Add(_e0);}}
        PrimaryAbilityMode = _buf.ReadString();
        {int n0 = _buf.ReadSize(); SavingThrowProficiencies = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); SavingThrowProficiencies.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ArmorProficiencies = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ArmorProficiencies.Add(_e0);}}
        {int n0 = _buf.ReadSize(); WeaponProficiencies = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); WeaponProficiencies.Add(_e0);}}
        SpellcastingAbility = _buf.ReadString();
        SpellSlotProgressionId = _buf.ReadString();
        Description = _buf.ReadString();
    }

    public static ClassDefine DeserializeClassDefine(ByteBuf _buf)
    {
        return new dnd.ClassDefine(_buf);
    }

    /// <summary>
    /// 职业唯一ID。
    /// </summary>
    public readonly string ClassId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 职业显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 生命骰面数，例如10表示d10。
    /// </summary>
    public readonly int HitDie;
    /// <summary>
    /// 主属性ID列表，多个用英文分号;分隔。
    /// </summary>
    public readonly System.Collections.Generic.List<string> PrimaryAbilityIds;
    /// <summary>
    /// 主属性关系：Fixed固定、AnyOne任选其一、All全部、Manual手动处理。
    /// </summary>
    public readonly string PrimaryAbilityMode;
    /// <summary>
    /// 豁免熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> SavingThrowProficiencies;
    /// <summary>
    /// 护甲熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ArmorProficiencies;
    /// <summary>
    /// 武器熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> WeaponProficiencies;
    /// <summary>
    /// 施法属性。无施法可留空。
    /// </summary>
    public readonly string SpellcastingAbility;
    /// <summary>
    /// 法术位进度表ID。第一版可留空或手动处理。
    /// </summary>
    public readonly string SpellSlotProgressionId;
    /// <summary>
    /// 用户录入的职业说明。
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -801275297;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "classId:" + ClassId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "hitDie:" + HitDie + ","
        + "primaryAbilityIds:" + Luban.StringUtil.CollectionToString(PrimaryAbilityIds) + ","
        + "primaryAbilityMode:" + PrimaryAbilityMode + ","
        + "savingThrowProficiencies:" + Luban.StringUtil.CollectionToString(SavingThrowProficiencies) + ","
        + "armorProficiencies:" + Luban.StringUtil.CollectionToString(ArmorProficiencies) + ","
        + "weaponProficiencies:" + Luban.StringUtil.CollectionToString(WeaponProficiencies) + ","
        + "spellcastingAbility:" + SpellcastingAbility + ","
        + "spellSlotProgressionId:" + SpellSlotProgressionId + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

