
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class FeatureEffect : Luban.BeanBase
{
    public FeatureEffect(ByteBuf _buf) 
    {
        EffectId = _buf.ReadString();
        EffectType = _buf.ReadString();
        Target = _buf.ReadString();
        Value = _buf.ReadString();
        Condition = _buf.ReadString();
        StackingRule = _buf.ReadString();
        ManualNote = _buf.ReadString();
    }

    public static FeatureEffect DeserializeFeatureEffect(ByteBuf _buf)
    {
        return new dnd.FeatureEffect(_buf);
    }

    /// <summary>
    /// 效果唯一ID。
    /// </summary>
    public readonly string EffectId;
    /// <summary>
    /// 结构化效果类型，参考 TbEnumList。
    /// </summary>
    public readonly string EffectType;
    /// <summary>
    /// 目标字段，例如 Athletics / Speed / ResourceId。
    /// </summary>
    public readonly string Target;
    /// <summary>
    /// 效果值。数字、公式或文本均可先以字符串保存。
    /// </summary>
    public readonly string Value;
    /// <summary>
    /// 触发条件或生效条件。第一版可留空。
    /// </summary>
    public readonly string Condition;
    /// <summary>
    /// 叠加规则：Stack / Replace / Highest / Unique。
    /// </summary>
    public readonly string StackingRule;
    /// <summary>
    /// 无法自动处理时的手动处理说明。
    /// </summary>
    public readonly string ManualNote;
   
    public const int __ID__ = -614561229;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "effectId:" + EffectId + ","
        + "effectType:" + EffectType + ","
        + "target:" + Target + ","
        + "value:" + Value + ","
        + "condition:" + Condition + ","
        + "stackingRule:" + StackingRule + ","
        + "manualNote:" + ManualNote + ","
        + "}";
    }
}
}

