
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class FeatureDefine : Luban.BeanBase
{
    public FeatureDefine(ByteBuf _buf) 
    {
        FeatureId = _buf.ReadString();
        PackageId = _buf.ReadString();
        Name = _buf.ReadString();
        FeatureType = _buf.ReadString();
        SourceRef = _buf.ReadString();
        {int n0 = _buf.ReadSize(); PrerequisiteIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); PrerequisiteIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); EffectIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); EffectIds.Add(_e0);}}
        Description = _buf.ReadString();
    }

    public static FeatureDefine DeserializeFeatureDefine(ByteBuf _buf)
    {
        return new dnd.FeatureDefine(_buf);
    }

    /// <summary>
    /// 特性唯一ID。职业、种族、背景、专长都可以引用。
    /// </summary>
    public readonly string FeatureId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 特性显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Class / Race / Background / Feat / Spell / Custom。
    /// </summary>
    public readonly string FeatureType;
    /// <summary>
    /// 来源引用，例如 custom_class:2。
    /// </summary>
    public readonly string SourceRef;
    /// <summary>
    /// 前置条件ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> PrerequisiteIds;
    /// <summary>
    /// 关联 TbFeatureEffect.effect_id 列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> EffectIds;
    /// <summary>
    /// 用户手动录入的描述文本。
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -644109731;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "featureId:" + FeatureId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "featureType:" + FeatureType + ","
        + "sourceRef:" + SourceRef + ","
        + "prerequisiteIds:" + Luban.StringUtil.CollectionToString(PrerequisiteIds) + ","
        + "effectIds:" + Luban.StringUtil.CollectionToString(EffectIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

