
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
/// <summary>
/// 背景定义表
/// </summary>
public partial class TbBackgroundDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.BackgroundDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.BackgroundDefine> _dataList;
    
    public TbBackgroundDefine(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.BackgroundDefine>(n);
        _dataList = new System.Collections.Generic.List<dnd.BackgroundDefine>(n);
        for(int i = n ; i > 0 ; --i)
        {
            dnd.BackgroundDefine _v;
            _v = global::GameConfig.dnd.BackgroundDefine.DeserializeBackgroundDefine(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.BackgroundId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.BackgroundDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.BackgroundDefine> DataList => _dataList;

    public dnd.BackgroundDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.BackgroundDefine Get(string key) => _dataMap[key];
    public dnd.BackgroundDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

