
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
/// <summary>
/// 选择组选项表。业务层按 choice_group_id + option_id 查询。
/// </summary>
public partial class TbChoiceOption
{
    private readonly System.Collections.Generic.List<dnd.ChoiceOption> _dataList;


    public TbChoiceOption(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<dnd.ChoiceOption>(n);
        for(int i = n ; i > 0 ; --i)
        {
            dnd.ChoiceOption _v;
            _v = global::GameConfig.dnd.ChoiceOption.DeserializeChoiceOption(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<dnd.ChoiceOption> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

