
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
/// <summary>
/// 职业法术列表关系表。业务层按 class_id + spell_id 查询。
/// </summary>
public partial class TbClassSpellList
{
    private readonly System.Collections.Generic.List<dnd.ClassSpellList> _dataList;


    public TbClassSpellList(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<dnd.ClassSpellList>(n);
        for(int i = n ; i > 0 ; --i)
        {
            dnd.ClassSpellList _v;
            _v = global::GameConfig.dnd.ClassSpellList.DeserializeClassSpellList(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<dnd.ClassSpellList> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

