
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
/// <summary>
/// 职业/种族/背景/专长/法术特性定义表
/// </summary>
public partial class TbFeatureDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.FeatureDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.FeatureDefine> _dataList;
    
    public TbFeatureDefine(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.FeatureDefine>(n);
        _dataList = new System.Collections.Generic.List<dnd.FeatureDefine>(n);
        for(int i = n ; i > 0 ; --i)
        {
            dnd.FeatureDefine _v;
            _v = global::GameConfig.dnd.FeatureDefine.DeserializeFeatureDefine(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.FeatureId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.FeatureDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.FeatureDefine> DataList => _dataList;

    public dnd.FeatureDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.FeatureDefine Get(string key) => _dataMap[key];
    public dnd.FeatureDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

