
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;

namespace GameConfig
{
public partial class Tables
{
    /// <summary>
    /// TEngine 示例道具表
    /// </summary>
    public item.TbItem TbItem {get; }
    /// <summary>
    /// 规则包定义表
    /// </summary>
    public dnd.TbRulePackage TbRulePackage {get; }
    /// <summary>
    /// 职业定义表
    /// </summary>
    public dnd.TbClassDefine TbClassDefine {get; }
    /// <summary>
    /// 职业1-20级成长表。业务层按 class_id + level 查询。
    /// </summary>
    public dnd.TbClassLevelProgression TbClassLevelProgression {get; }
    /// <summary>
    /// 职业/种族/背景/专长/法术特性定义表
    /// </summary>
    public dnd.TbFeatureDefine TbFeatureDefine {get; }
    /// <summary>
    /// 结构化特性效果表
    /// </summary>
    public dnd.TbFeatureEffect TbFeatureEffect {get; }
    /// <summary>
    /// 角色创建与升级选择组表
    /// </summary>
    public dnd.TbChoiceGroup TbChoiceGroup {get; }
    /// <summary>
    /// 选择组选项表。业务层按 choice_group_id + option_id 查询。
    /// </summary>
    public dnd.TbChoiceOption TbChoiceOption {get; }
    /// <summary>
    /// 种族/血统定义表
    /// </summary>
    public dnd.TbRaceDefine TbRaceDefine {get; }
    /// <summary>
    /// 背景定义表
    /// </summary>
    public dnd.TbBackgroundDefine TbBackgroundDefine {get; }
    /// <summary>
    /// 专长定义表
    /// </summary>
    public dnd.TbFeatDefine TbFeatDefine {get; }
    /// <summary>
    /// 法术定义表
    /// </summary>
    public dnd.TbSpellDefine TbSpellDefine {get; }
    /// <summary>
    /// 职业法术列表关系表。业务层按 class_id + spell_id 查询。
    /// </summary>
    public dnd.TbClassSpellList TbClassSpellList {get; }
    /// <summary>
    /// 外部枚举/字典值表。业务层按 enum_type + value 查询。
    /// </summary>
    public dnd.TbEnumList TbEnumList {get; }

    public Tables(System.Func<string, ByteBuf> loader)
    {
        TbItem = new item.TbItem(loader("item_tbitem"));
        TbRulePackage = new dnd.TbRulePackage(loader("dnd_tbrulepackage"));
        TbClassDefine = new dnd.TbClassDefine(loader("dnd_tbclassdefine"));
        TbClassLevelProgression = new dnd.TbClassLevelProgression(loader("dnd_tbclasslevelprogression"));
        TbFeatureDefine = new dnd.TbFeatureDefine(loader("dnd_tbfeaturedefine"));
        TbFeatureEffect = new dnd.TbFeatureEffect(loader("dnd_tbfeatureeffect"));
        TbChoiceGroup = new dnd.TbChoiceGroup(loader("dnd_tbchoicegroup"));
        TbChoiceOption = new dnd.TbChoiceOption(loader("dnd_tbchoiceoption"));
        TbRaceDefine = new dnd.TbRaceDefine(loader("dnd_tbracedefine"));
        TbBackgroundDefine = new dnd.TbBackgroundDefine(loader("dnd_tbbackgrounddefine"));
        TbFeatDefine = new dnd.TbFeatDefine(loader("dnd_tbfeatdefine"));
        TbSpellDefine = new dnd.TbSpellDefine(loader("dnd_tbspelldefine"));
        TbClassSpellList = new dnd.TbClassSpellList(loader("dnd_tbclassspelllist"));
        TbEnumList = new dnd.TbEnumList(loader("dnd_tbenumlist"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbItem.ResolveRef(this);
        TbRulePackage.ResolveRef(this);
        TbClassDefine.ResolveRef(this);
        TbClassLevelProgression.ResolveRef(this);
        TbFeatureDefine.ResolveRef(this);
        TbFeatureEffect.ResolveRef(this);
        TbChoiceGroup.ResolveRef(this);
        TbChoiceOption.ResolveRef(this);
        TbRaceDefine.ResolveRef(this);
        TbBackgroundDefine.ResolveRef(this);
        TbFeatDefine.ResolveRef(this);
        TbSpellDefine.ResolveRef(this);
        TbClassSpellList.ResolveRef(this);
        TbEnumList.ResolveRef(this);
    }
}

}
