
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace GameConfig
{
public partial class Tables
{
    #region The Tables

    /// <summary>
    /// TEngine 示例道具表
    /// </summary>
    private item.TbItem m_TbItem;
    public item.TbItem TbItem
    {
        get
        {
            if (m_TbItem == null)
            {
                m_TbItem = new item.TbItem(defaultLoader("item_tbitem"));
                m_TbItem.ResolveRef(this);
            }
            return m_TbItem;
        }
        set
        {
            m_TbItem = value;
            m_TbItem.ResolveRef(this);
        }
    }
    /// <summary>
    /// 规则包定义表
    /// </summary>
    private dnd.TbRulePackage m_TbRulePackage;
    public dnd.TbRulePackage TbRulePackage
    {
        get
        {
            if (m_TbRulePackage == null)
            {
                m_TbRulePackage = new dnd.TbRulePackage(defaultLoader("dnd_tbrulepackage"));
                m_TbRulePackage.ResolveRef(this);
            }
            return m_TbRulePackage;
        }
        set
        {
            m_TbRulePackage = value;
            m_TbRulePackage.ResolveRef(this);
        }
    }
    /// <summary>
    /// 职业定义表
    /// </summary>
    private dnd.TbClassDefine m_TbClassDefine;
    public dnd.TbClassDefine TbClassDefine
    {
        get
        {
            if (m_TbClassDefine == null)
            {
                m_TbClassDefine = new dnd.TbClassDefine(defaultLoader("dnd_tbclassdefine"));
                m_TbClassDefine.ResolveRef(this);
            }
            return m_TbClassDefine;
        }
        set
        {
            m_TbClassDefine = value;
            m_TbClassDefine.ResolveRef(this);
        }
    }
    /// <summary>
    /// 职业1-20级成长表。业务层按 class_id + level 查询。
    /// </summary>
    private dnd.TbClassLevelProgression m_TbClassLevelProgression;
    public dnd.TbClassLevelProgression TbClassLevelProgression
    {
        get
        {
            if (m_TbClassLevelProgression == null)
            {
                m_TbClassLevelProgression = new dnd.TbClassLevelProgression(defaultLoader("dnd_tbclasslevelprogression"));
                m_TbClassLevelProgression.ResolveRef(this);
            }
            return m_TbClassLevelProgression;
        }
        set
        {
            m_TbClassLevelProgression = value;
            m_TbClassLevelProgression.ResolveRef(this);
        }
    }
    /// <summary>
    /// 职业/种族/背景/专长/法术特性定义表
    /// </summary>
    private dnd.TbFeatureDefine m_TbFeatureDefine;
    public dnd.TbFeatureDefine TbFeatureDefine
    {
        get
        {
            if (m_TbFeatureDefine == null)
            {
                m_TbFeatureDefine = new dnd.TbFeatureDefine(defaultLoader("dnd_tbfeaturedefine"));
                m_TbFeatureDefine.ResolveRef(this);
            }
            return m_TbFeatureDefine;
        }
        set
        {
            m_TbFeatureDefine = value;
            m_TbFeatureDefine.ResolveRef(this);
        }
    }
    /// <summary>
    /// 结构化特性效果表
    /// </summary>
    private dnd.TbFeatureEffect m_TbFeatureEffect;
    public dnd.TbFeatureEffect TbFeatureEffect
    {
        get
        {
            if (m_TbFeatureEffect == null)
            {
                m_TbFeatureEffect = new dnd.TbFeatureEffect(defaultLoader("dnd_tbfeatureeffect"));
                m_TbFeatureEffect.ResolveRef(this);
            }
            return m_TbFeatureEffect;
        }
        set
        {
            m_TbFeatureEffect = value;
            m_TbFeatureEffect.ResolveRef(this);
        }
    }
    /// <summary>
    /// 角色创建与升级选择组表
    /// </summary>
    private dnd.TbChoiceGroup m_TbChoiceGroup;
    public dnd.TbChoiceGroup TbChoiceGroup
    {
        get
        {
            if (m_TbChoiceGroup == null)
            {
                m_TbChoiceGroup = new dnd.TbChoiceGroup(defaultLoader("dnd_tbchoicegroup"));
                m_TbChoiceGroup.ResolveRef(this);
            }
            return m_TbChoiceGroup;
        }
        set
        {
            m_TbChoiceGroup = value;
            m_TbChoiceGroup.ResolveRef(this);
        }
    }
    /// <summary>
    /// 选择组选项表。业务层按 choice_group_id + option_id 查询。
    /// </summary>
    private dnd.TbChoiceOption m_TbChoiceOption;
    public dnd.TbChoiceOption TbChoiceOption
    {
        get
        {
            if (m_TbChoiceOption == null)
            {
                m_TbChoiceOption = new dnd.TbChoiceOption(defaultLoader("dnd_tbchoiceoption"));
                m_TbChoiceOption.ResolveRef(this);
            }
            return m_TbChoiceOption;
        }
        set
        {
            m_TbChoiceOption = value;
            m_TbChoiceOption.ResolveRef(this);
        }
    }
    /// <summary>
    /// 种族/血统定义表
    /// </summary>
    private dnd.TbRaceDefine m_TbRaceDefine;
    public dnd.TbRaceDefine TbRaceDefine
    {
        get
        {
            if (m_TbRaceDefine == null)
            {
                m_TbRaceDefine = new dnd.TbRaceDefine(defaultLoader("dnd_tbracedefine"));
                m_TbRaceDefine.ResolveRef(this);
            }
            return m_TbRaceDefine;
        }
        set
        {
            m_TbRaceDefine = value;
            m_TbRaceDefine.ResolveRef(this);
        }
    }
    /// <summary>
    /// 背景定义表
    /// </summary>
    private dnd.TbBackgroundDefine m_TbBackgroundDefine;
    public dnd.TbBackgroundDefine TbBackgroundDefine
    {
        get
        {
            if (m_TbBackgroundDefine == null)
            {
                m_TbBackgroundDefine = new dnd.TbBackgroundDefine(defaultLoader("dnd_tbbackgrounddefine"));
                m_TbBackgroundDefine.ResolveRef(this);
            }
            return m_TbBackgroundDefine;
        }
        set
        {
            m_TbBackgroundDefine = value;
            m_TbBackgroundDefine.ResolveRef(this);
        }
    }
    /// <summary>
    /// 专长定义表
    /// </summary>
    private dnd.TbFeatDefine m_TbFeatDefine;
    public dnd.TbFeatDefine TbFeatDefine
    {
        get
        {
            if (m_TbFeatDefine == null)
            {
                m_TbFeatDefine = new dnd.TbFeatDefine(defaultLoader("dnd_tbfeatdefine"));
                m_TbFeatDefine.ResolveRef(this);
            }
            return m_TbFeatDefine;
        }
        set
        {
            m_TbFeatDefine = value;
            m_TbFeatDefine.ResolveRef(this);
        }
    }
    /// <summary>
    /// 法术定义表
    /// </summary>
    private dnd.TbSpellDefine m_TbSpellDefine;
    public dnd.TbSpellDefine TbSpellDefine
    {
        get
        {
            if (m_TbSpellDefine == null)
            {
                m_TbSpellDefine = new dnd.TbSpellDefine(defaultLoader("dnd_tbspelldefine"));
                m_TbSpellDefine.ResolveRef(this);
            }
            return m_TbSpellDefine;
        }
        set
        {
            m_TbSpellDefine = value;
            m_TbSpellDefine.ResolveRef(this);
        }
    }
    /// <summary>
    /// 职业法术列表关系表。业务层按 class_id + spell_id 查询。
    /// </summary>
    private dnd.TbClassSpellList m_TbClassSpellList;
    public dnd.TbClassSpellList TbClassSpellList
    {
        get
        {
            if (m_TbClassSpellList == null)
            {
                m_TbClassSpellList = new dnd.TbClassSpellList(defaultLoader("dnd_tbclassspelllist"));
                m_TbClassSpellList.ResolveRef(this);
            }
            return m_TbClassSpellList;
        }
        set
        {
            m_TbClassSpellList = value;
            m_TbClassSpellList.ResolveRef(this);
        }
    }
    /// <summary>
    /// 外部枚举/字典值表。业务层按 enum_type + value 查询。
    /// </summary>
    private dnd.TbEnumList m_TbEnumList;
    public dnd.TbEnumList TbEnumList
    {
        get
        {
            if (m_TbEnumList == null)
            {
                m_TbEnumList = new dnd.TbEnumList(defaultLoader("dnd_tbenumlist"));
                m_TbEnumList.ResolveRef(this);
            }
            return m_TbEnumList;
        }
        set
        {
            m_TbEnumList = value;
            m_TbEnumList.ResolveRef(this);
        }
    }

    #endregion

    System.Func<string, JArray> defaultLoader;

    public Tables(System.Func<string, JArray> loader)
    {
        SetDefaultLoader(loader);
        Init();
    }

    public void SetDefaultLoader(System.Func<string, JArray> loader)
    {
        defaultLoader = null;
        defaultLoader = loader;
    }

    //public partial void Init();

    public void Init(){}
}

}

