//----------------------------------------------------------
// <auto-generated>
// -This code was generated.
// -Changes to this file may cause incorrect behavior.
// -will be lost if the code is regenerated.
// <auto-generated/>
//----------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using TEngine;
using UnityEngine;

namespace GameLogic
{
    [DisallowMultipleComponent]
    public partial class UIBindComponent : MonoBehaviour
    {
        [SerializeField] private List<Component> m_components = new List<Component>();

        public T GetComponent<T>(int index) where T : Component
        {
            if (index < 0 || index >= m_components.Count)
            {
                Log.Error("索引超出范围");
                return null;
            }

            Component raw = m_components[index];
            if (raw == null)
            {
                // 此槽位在 Prefab 中为空（fileID: 0），属于设计上的缺省，静默返回 null
                return null;
            }

            T c = raw as T;
            if (c == null)
            {
                Log.Error($"没有找到对应类型: {typeof(T).FullName}");
                return null;
            }
            return c;
        }
    }
}