
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class Alignment : Luban.BeanBase
{
    public Alignment(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        AlignmentId = (string)_obj.GetValue("alignment_id");
        Name = (string)_obj.GetValue("name");
        Description = (string)_obj.GetValue("description");
    }

    public static Alignment DeserializeAlignment(JToken _buf)
    {
        return new dnd.Alignment(_buf);
    }

    /// <summary>
    /// 阵营唯一ID。
    /// </summary>
    public readonly string AlignmentId;
    /// <summary>
    /// 阵营显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = 1759347183;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "alignmentId:" + AlignmentId + ","
        + "name:" + Name + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

