
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class BackgroundDefine : Luban.BeanBase
{
    public BackgroundDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        BackgroundId = (string)_obj.GetValue("background_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        { var __json0 = _obj.GetValue("skill_proficiencies"); SkillProficiencies = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  SkillProficiencies.Add(__v0); }   }
        { var __json0 = _obj.GetValue("tool_proficiencies"); ToolProficiencies = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ToolProficiencies.Add(__v0); }   }
        { var __json0 = _obj.GetValue("language_ids"); LanguageIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  LanguageIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("feature_ids"); FeatureIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  FeatureIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("equipment_grant_ids"); EquipmentGrantIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  EquipmentGrantIds.Add(__v0); }   }
        Description = (string)_obj.GetValue("description");
    }

    public static BackgroundDefine DeserializeBackgroundDefine(JToken _buf)
    {
        return new dnd.BackgroundDefine(_buf);
    }

    /// <summary>
    /// 背景唯一ID。
    /// </summary>
    public readonly string BackgroundId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 技能熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> SkillProficiencies;
    /// <summary>
    /// 工具熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ToolProficiencies;
    /// <summary>
    /// 语言列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> LanguageIds;
    /// <summary>
    /// 背景特性列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeatureIds;
    /// <summary>
    /// 装备授予。第一版可留空。
    /// </summary>
    public readonly System.Collections.Generic.List<string> EquipmentGrantIds;
    /// <summary>
    /// 用户录入说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = 991967997;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "backgroundId:" + BackgroundId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "skillProficiencies:" + Luban.StringUtil.CollectionToString(SkillProficiencies) + ","
        + "toolProficiencies:" + Luban.StringUtil.CollectionToString(ToolProficiencies) + ","
        + "languageIds:" + Luban.StringUtil.CollectionToString(LanguageIds) + ","
        + "featureIds:" + Luban.StringUtil.CollectionToString(FeatureIds) + ","
        + "equipmentGrantIds:" + Luban.StringUtil.CollectionToString(EquipmentGrantIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

