
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class ChoiceOption : Luban.BeanBase
{
    public ChoiceOption(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ChoiceGroupId = (string)_obj.GetValue("choice_group_id");
        OptionId = (string)_obj.GetValue("option_id");
        Name = (string)_obj.GetValue("name");
        { var __json0 = _obj.GetValue("grant_feature_ids"); GrantFeatureIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  GrantFeatureIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("grant_effect_ids"); GrantEffectIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  GrantEffectIds.Add(__v0); }   }
        Description = (string)_obj.GetValue("description");
    }

    public static ChoiceOption DeserializeChoiceOption(JToken _buf)
    {
        return new dnd.ChoiceOption(_buf);
    }

    /// <summary>
    /// 所属选择组ID。
    /// </summary>
    public readonly string ChoiceGroupId;
    /// <summary>
    /// 选项唯一ID。
    /// </summary>
    public readonly string OptionId;
    /// <summary>
    /// 选项显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 选择后授予的特性ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> GrantFeatureIds;
    /// <summary>
    /// 选择后直接授予的效果ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> GrantEffectIds;
    /// <summary>
    /// 用户录入说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -1545999894;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "choiceGroupId:" + ChoiceGroupId + ","
        + "optionId:" + OptionId + ","
        + "name:" + Name + ","
        + "grantFeatureIds:" + Luban.StringUtil.CollectionToString(GrantFeatureIds) + ","
        + "grantEffectIds:" + Luban.StringUtil.CollectionToString(GrantEffectIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

