
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class ChoiceGroup : Luban.BeanBase
{
    public ChoiceGroup(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ChoiceGroupId = (string)_obj.GetValue("choice_group_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        ChoiceType = (string)_obj.GetValue("choice_type");
        MinSelect = (int)_obj.GetValue("min_select");
        MaxSelect = (int)_obj.GetValue("max_select");
        OptionFilter = (string)_obj.GetValue("option_filter");
        Description = (string)_obj.GetValue("description");
    }

    public static ChoiceGroup DeserializeChoiceGroup(JToken _buf)
    {
        return new dnd.ChoiceGroup(_buf);
    }

    /// <summary>
    /// 选择组唯一ID。
    /// </summary>
    public readonly string ChoiceGroupId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 选择组显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Feature / Skill / Spell / Feat / AbilityScore / Custom。
    /// </summary>
    public readonly string ChoiceType;
    /// <summary>
    /// 至少选择数量。
    /// </summary>
    public readonly int MinSelect;
    /// <summary>
    /// 最多选择数量。
    /// </summary>
    public readonly int MaxSelect;
    /// <summary>
    /// 可选过滤条件。第一版可留空。
    /// </summary>
    public readonly string OptionFilter;
    /// <summary>
    /// 说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -195751318;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "choiceGroupId:" + ChoiceGroupId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "choiceType:" + ChoiceType + ","
        + "minSelect:" + MinSelect + ","
        + "maxSelect:" + MaxSelect + ","
        + "optionFilter:" + OptionFilter + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

