
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class ChoiceGroup : Luban.BeanBase
{
    public ChoiceGroup(ByteBuf _buf) 
    {
        ChoiceGroupId = _buf.ReadString();
        PackageId = _buf.ReadString();
        Name = _buf.ReadString();
        ChoiceType = _buf.ReadString();
        MinSelect = _buf.ReadInt();
        MaxSelect = _buf.ReadInt();
        OptionFilter = _buf.ReadString();
        Description = _buf.ReadString();
    }

    public static ChoiceGroup DeserializeChoiceGroup(ByteBuf _buf)
    {
        return new dnd.ChoiceGroup(_buf);
    }

    /// <summary>
    /// 选择组唯一ID。
    /// </summary>
    public readonly string ChoiceGroupId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 选择组显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Feature / Skill / Spell / Feat / AbilityScore / Custom。
    /// </summary>
    public readonly string ChoiceType;
    /// <summary>
    /// 至少选择数量。
    /// </summary>
    public readonly int MinSelect;
    /// <summary>
    /// 最多选择数量。
    /// </summary>
    public readonly int MaxSelect;
    /// <summary>
    /// 可选过滤条件。第一版可留空。
    /// </summary>
    public readonly string OptionFilter;
    /// <summary>
    /// 说明。
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -195751318;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "choiceGroupId:" + ChoiceGroupId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "choiceType:" + ChoiceType + ","
        + "minSelect:" + MinSelect + ","
        + "maxSelect:" + MaxSelect + ","
        + "optionFilter:" + OptionFilter + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

