
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class ClassLevelProgression : Luban.BeanBase
{
    public ClassLevelProgression(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ClassId = (string)_obj.GetValue("class_id");
        Level = (int)_obj.GetValue("level");
        ProficiencyBonus = (int)_obj.GetValue("proficiency_bonus");
        FixedHpGain = (int)_obj.GetValue("fixed_hp_gain");
        { var __json0 = _obj.GetValue("feature_ids"); FeatureIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  FeatureIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("choice_group_ids"); ChoiceGroupIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ChoiceGroupIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("resource_grant_ids"); ResourceGrantIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ResourceGrantIds.Add(__v0); }   }
        {if (_obj.TryGetValue("spell_slot_progression_level", out var _j)) { SpellSlotProgressionLevel = (int)_j; } else { SpellSlotProgressionLevel = null; } }
        {if (_obj.TryGetValue("cantrip_known", out var _j)) { CantripKnown = (int)_j; } else { CantripKnown = null; } }
        {if (_obj.TryGetValue("spell_known", out var _j)) { SpellKnown = (int)_j; } else { SpellKnown = null; } }
        PreparedSpellFormula = (string)_obj.GetValue("prepared_spell_formula");
        AsiAvailable = (bool)_obj.GetValue("asi_available");
        SubclassFeature = (bool)_obj.GetValue("subclass_feature");
        Note = (string)_obj.GetValue("note");
    }

    public static ClassLevelProgression DeserializeClassLevelProgression(JToken _buf)
    {
        return new dnd.ClassLevelProgression(_buf);
    }

    /// <summary>
    /// 职业ID，引用 TbClassDefine.class_id。
    /// </summary>
    public readonly string ClassId;
    /// <summary>
    /// 职业等级，范围1-20。
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 该等级熟练加值。
    /// </summary>
    public readonly int ProficiencyBonus;
    /// <summary>
    /// 升级到该等级时的固定HP增长；若使用掷骰或手动HP，可填0。
    /// </summary>
    public readonly int FixedHpGain;
    /// <summary>
    /// 本等级自动获得的特性ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeatureIds;
    /// <summary>
    /// 本等级需要玩家选择的选择组ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ChoiceGroupIds;
    /// <summary>
    /// 本等级授予或刷新资源的ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ResourceGrantIds;
    /// <summary>
    /// 施法进度等级；非施法职业可填null。
    /// </summary>
    public readonly int? SpellSlotProgressionLevel;
    /// <summary>
    /// 该等级已知戏法数量；不适用可填null。
    /// </summary>
    public readonly int? CantripKnown;
    /// <summary>
    /// 该等级已知法术数量；不适用可填null。
    /// </summary>
    public readonly int? SpellKnown;
    /// <summary>
    /// 准备法术数量公式，例如 level+WisMod；不适用留空。
    /// </summary>
    public readonly string PreparedSpellFormula;
    /// <summary>
    /// 该等级是否获得属性提升/专长选择机会。
    /// </summary>
    public readonly bool AsiAvailable;
    /// <summary>
    /// 该等级是否获得子职业相关特性。
    /// </summary>
    public readonly bool SubclassFeature;
    /// <summary>
    /// 备注，仅用于编辑说明。
    /// </summary>
    public readonly string Note;


    public const int __ID__ = 356427835;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "classId:" + ClassId + ","
        + "level:" + Level + ","
        + "proficiencyBonus:" + ProficiencyBonus + ","
        + "fixedHpGain:" + FixedHpGain + ","
        + "featureIds:" + Luban.StringUtil.CollectionToString(FeatureIds) + ","
        + "choiceGroupIds:" + Luban.StringUtil.CollectionToString(ChoiceGroupIds) + ","
        + "resourceGrantIds:" + Luban.StringUtil.CollectionToString(ResourceGrantIds) + ","
        + "spellSlotProgressionLevel:" + SpellSlotProgressionLevel + ","
        + "cantripKnown:" + CantripKnown + ","
        + "spellKnown:" + SpellKnown + ","
        + "preparedSpellFormula:" + PreparedSpellFormula + ","
        + "asiAvailable:" + AsiAvailable + ","
        + "subclassFeature:" + SubclassFeature + ","
        + "note:" + Note + ","
        + "}";
    }
}
}

