
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class ClassDefine : Luban.BeanBase
{
    public ClassDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ClassId = (string)_obj.GetValue("class_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        HitDie = (int)_obj.GetValue("hit_die");
        { var __json0 = _obj.GetValue("primary_ability_ids"); PrimaryAbilityIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  PrimaryAbilityIds.Add(__v0); }   }
        PrimaryAbilityMode = (string)_obj.GetValue("primary_ability_mode");
        { var __json0 = _obj.GetValue("saving_throw_proficiencies"); SavingThrowProficiencies = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  SavingThrowProficiencies.Add(__v0); }   }
        { var __json0 = _obj.GetValue("armor_proficiencies"); ArmorProficiencies = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ArmorProficiencies.Add(__v0); }   }
        { var __json0 = _obj.GetValue("weapon_proficiencies"); WeaponProficiencies = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  WeaponProficiencies.Add(__v0); }   }
        SpellcastingAbility = (string)_obj.GetValue("spellcasting_ability");
        SpellSlotProgressionId = (string)_obj.GetValue("spell_slot_progression_id");
        Description = (string)_obj.GetValue("description");
    }

    public static ClassDefine DeserializeClassDefine(JToken _buf)
    {
        return new dnd.ClassDefine(_buf);
    }

    /// <summary>
    /// 职业唯一ID。
    /// </summary>
    public readonly string ClassId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 职业显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 生命骰面数，例如10表示d10。
    /// </summary>
    public readonly int HitDie;
    /// <summary>
    /// 主属性ID列表，多个用英文分号;分隔。
    /// </summary>
    public readonly System.Collections.Generic.List<string> PrimaryAbilityIds;
    /// <summary>
    /// 主属性关系：Fixed固定、AnyOne任选其一、All全部、Manual手动处理。
    /// </summary>
    public readonly string PrimaryAbilityMode;
    /// <summary>
    /// 豁免熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> SavingThrowProficiencies;
    /// <summary>
    /// 护甲熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ArmorProficiencies;
    /// <summary>
    /// 武器熟练列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> WeaponProficiencies;
    /// <summary>
    /// 施法属性。无施法可留空。
    /// </summary>
    public readonly string SpellcastingAbility;
    /// <summary>
    /// 法术位进度表ID。第一版可留空或手动处理。
    /// </summary>
    public readonly string SpellSlotProgressionId;
    /// <summary>
    /// 用户录入的职业说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -801275297;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "classId:" + ClassId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "hitDie:" + HitDie + ","
        + "primaryAbilityIds:" + Luban.StringUtil.CollectionToString(PrimaryAbilityIds) + ","
        + "primaryAbilityMode:" + PrimaryAbilityMode + ","
        + "savingThrowProficiencies:" + Luban.StringUtil.CollectionToString(SavingThrowProficiencies) + ","
        + "armorProficiencies:" + Luban.StringUtil.CollectionToString(ArmorProficiencies) + ","
        + "weaponProficiencies:" + Luban.StringUtil.CollectionToString(WeaponProficiencies) + ","
        + "spellcastingAbility:" + SpellcastingAbility + ","
        + "spellSlotProgressionId:" + SpellSlotProgressionId + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

