
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class ClassLevelProgression : Luban.BeanBase
{
    public ClassLevelProgression(ByteBuf _buf) 
    {
        ClassId = _buf.ReadString();
        Level = _buf.ReadInt();
        ProficiencyBonus = _buf.ReadInt();
        FixedHpGain = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); FeatureIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); FeatureIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ChoiceGroupIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ChoiceGroupIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ResourceGrantIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ResourceGrantIds.Add(_e0);}}
        if(_buf.ReadBool()){ SpellSlotProgressionLevel = _buf.ReadInt(); } else { SpellSlotProgressionLevel = null; }
        if(_buf.ReadBool()){ CantripKnown = _buf.ReadInt(); } else { CantripKnown = null; }
        if(_buf.ReadBool()){ SpellKnown = _buf.ReadInt(); } else { SpellKnown = null; }
        PreparedSpellFormula = _buf.ReadString();
        AsiAvailable = _buf.ReadBool();
        SubclassFeature = _buf.ReadBool();
        Note = _buf.ReadString();
    }

    public static ClassLevelProgression DeserializeClassLevelProgression(ByteBuf _buf)
    {
        return new dnd.ClassLevelProgression(_buf);
    }

    /// <summary>
    /// 职业ID，引用 TbClassDefine.class_id。
    /// </summary>
    public readonly string ClassId;
    /// <summary>
    /// 职业等级，范围1-20。
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 该等级熟练加值。
    /// </summary>
    public readonly int ProficiencyBonus;
    /// <summary>
    /// 升级到该等级时的固定HP增长；若使用掷骰或手动HP，可填0。
    /// </summary>
    public readonly int FixedHpGain;
    /// <summary>
    /// 本等级自动获得的特性ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeatureIds;
    /// <summary>
    /// 本等级需要玩家选择的选择组ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ChoiceGroupIds;
    /// <summary>
    /// 本等级授予或刷新资源的ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ResourceGrantIds;
    /// <summary>
    /// 施法进度等级；非施法职业可填null。
    /// </summary>
    public readonly int? SpellSlotProgressionLevel;
    /// <summary>
    /// 该等级已知戏法数量；不适用可填null。
    /// </summary>
    public readonly int? CantripKnown;
    /// <summary>
    /// 该等级已知法术数量；不适用可填null。
    /// </summary>
    public readonly int? SpellKnown;
    /// <summary>
    /// 准备法术数量公式，例如 level+WisMod；不适用留空。
    /// </summary>
    public readonly string PreparedSpellFormula;
    /// <summary>
    /// 该等级是否获得属性提升/专长选择机会。
    /// </summary>
    public readonly bool AsiAvailable;
    /// <summary>
    /// 该等级是否获得子职业相关特性。
    /// </summary>
    public readonly bool SubclassFeature;
    /// <summary>
    /// 备注，仅用于编辑说明。
    /// </summary>
    public readonly string Note;
   
    public const int __ID__ = 356427835;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "classId:" + ClassId + ","
        + "level:" + Level + ","
        + "proficiencyBonus:" + ProficiencyBonus + ","
        + "fixedHpGain:" + FixedHpGain + ","
        + "featureIds:" + Luban.StringUtil.CollectionToString(FeatureIds) + ","
        + "choiceGroupIds:" + Luban.StringUtil.CollectionToString(ChoiceGroupIds) + ","
        + "resourceGrantIds:" + Luban.StringUtil.CollectionToString(ResourceGrantIds) + ","
        + "spellSlotProgressionLevel:" + SpellSlotProgressionLevel + ","
        + "cantripKnown:" + CantripKnown + ","
        + "spellKnown:" + SpellKnown + ","
        + "preparedSpellFormula:" + PreparedSpellFormula + ","
        + "asiAvailable:" + AsiAvailable + ","
        + "subclassFeature:" + SubclassFeature + ","
        + "note:" + Note + ","
        + "}";
    }
}
}

