
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class ClassSpellList : Luban.BeanBase
{
    public ClassSpellList(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ClassId = (string)_obj.GetValue("class_id");
        SpellId = (string)_obj.GetValue("spell_id");
        MinClassLevel = (int)_obj.GetValue("min_class_level");
        AlwaysPrepared = (bool)_obj.GetValue("always_prepared");
        SourceFeatureId = (string)_obj.GetValue("source_feature_id");
        Note = (string)_obj.GetValue("note");
    }

    public static ClassSpellList DeserializeClassSpellList(JToken _buf)
    {
        return new dnd.ClassSpellList(_buf);
    }

    /// <summary>
    /// 职业ID。
    /// </summary>
    public readonly string ClassId;
    /// <summary>
    /// 法术ID。
    /// </summary>
    public readonly string SpellId;
    /// <summary>
    /// 最小职业等级。
    /// </summary>
    public readonly int MinClassLevel;
    /// <summary>
    /// 是否总是准备。
    /// </summary>
    public readonly bool AlwaysPrepared;
    /// <summary>
    /// 如果由特性授予，填写来源FeatureId。
    /// </summary>
    public readonly string SourceFeatureId;
    /// <summary>
    /// 备注。
    /// </summary>
    public readonly string Note;


    public const int __ID__ = 480786114;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "classId:" + ClassId + ","
        + "spellId:" + SpellId + ","
        + "minClassLevel:" + MinClassLevel + ","
        + "alwaysPrepared:" + AlwaysPrepared + ","
        + "sourceFeatureId:" + SourceFeatureId + ","
        + "note:" + Note + ","
        + "}";
    }
}
}

