
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class DndItemTypeDefine : Luban.BeanBase
{
    public DndItemTypeDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ItemTypeId = (string)_obj.GetValue("item_type_id");
        ParentTypeId = (string)_obj.GetValue("parent_type_id");
        Name = (string)_obj.GetValue("name");
        Selectable = (bool)_obj.GetValue("selectable");
        CanUseByDefault = (bool)_obj.GetValue("can_use_by_default");
        StackableByDefault = (bool)_obj.GetValue("stackable_by_default");
        ConsumeQuantityOnUseByDefault = (bool)_obj.GetValue("consume_quantity_on_use_by_default");
        CanHaveCharges = (bool)_obj.GetValue("can_have_charges");
        ConsumeChargeOnUseByDefault = (bool)_obj.GetValue("consume_charge_on_use_by_default");
        IsEquipmentType = (bool)_obj.GetValue("is_equipment_type");
        DefaultEquipmentSlot = (string)_obj.GetValue("default_equipment_slot");
        SortOrder = (int)_obj.GetValue("sort_order");
        Description = (string)_obj.GetValue("description");
    }

    public static DndItemTypeDefine DeserializeDndItemTypeDefine(JToken _buf)
    {
        return new dnd.DndItemTypeDefine(_buf);
    }

    /// <summary>
    /// 物品类型唯一ID。
    /// </summary>
    public readonly string ItemTypeId;
    /// <summary>
    /// 父类型ID；无父类型可留空。
    /// </summary>
    public readonly string ParentTypeId;
    /// <summary>
    /// 物品类型显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 是否允许用户在物品录入UI中选择。父类型通常为false。
    /// </summary>
    public readonly bool Selectable;
    /// <summary>
    /// 该类型默认是否支持背包中的使用动作。
    /// </summary>
    public readonly bool CanUseByDefault;
    /// <summary>
    /// 该类型默认是否可以堆叠显示与存储。
    /// </summary>
    public readonly bool StackableByDefault;
    /// <summary>
    /// 该类型默认使用后是否减少数量。
    /// </summary>
    public readonly bool ConsumeQuantityOnUseByDefault;
    /// <summary>
    /// 该类型是否支持充能次数字段。
    /// </summary>
    public readonly bool CanHaveCharges;
    /// <summary>
    /// 该类型默认使用后是否消耗充能次数。
    /// </summary>
    public readonly bool ConsumeChargeOnUseByDefault;
    /// <summary>
    /// 该类型是否标识为装备类物品。第一阶段只做标识，不做装备校验。
    /// </summary>
    public readonly bool IsEquipmentType;
    /// <summary>
    /// 默认装备位置标识；第一阶段只做标识。
    /// </summary>
    public readonly string DefaultEquipmentSlot;
    /// <summary>
    /// UI排序值，数值越小越靠前。
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 类型说明。具体物品的是否魔法、稀有度、是否需要同调不在本表判断。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -2127049522;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "itemTypeId:" + ItemTypeId + ","
        + "parentTypeId:" + ParentTypeId + ","
        + "name:" + Name + ","
        + "selectable:" + Selectable + ","
        + "canUseByDefault:" + CanUseByDefault + ","
        + "stackableByDefault:" + StackableByDefault + ","
        + "consumeQuantityOnUseByDefault:" + ConsumeQuantityOnUseByDefault + ","
        + "canHaveCharges:" + CanHaveCharges + ","
        + "consumeChargeOnUseByDefault:" + ConsumeChargeOnUseByDefault + ","
        + "isEquipmentType:" + IsEquipmentType + ","
        + "defaultEquipmentSlot:" + DefaultEquipmentSlot + ","
        + "sortOrder:" + SortOrder + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

