
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;

namespace GameConfig.dnd
{
public sealed partial class DndItemDefine : Luban.BeanBase
{
    public DndItemDefine(JToken _buf)
    {
        JObject _obj = _buf as JObject;
        ItemId = (string)_obj.GetValue("item_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        ItemType = (string)_obj.GetValue("item_type");
        Rarity = (string)_obj.GetValue("rarity");
        Description = (string)_obj.GetValue("description");
        SourceBook = (string)_obj.GetValue("source_book");
        SourcePage = (string)_obj.GetValue("source_page");
        Stackable = (bool)_obj.GetValue("stackable");
        MaxStack = (int)_obj.GetValue("max_stack");
        Weight = (float)_obj.GetValue("weight");
        PriceGp = (int)_obj.GetValue("price_gp");
        IsEquippable = (bool)_obj.GetValue("is_equippable");
        DefaultQuantity = (int)_obj.GetValue("default_quantity");
        EquipmentSlot = (string)_obj.GetValue("equipment_slot");
        RequiresAttunement = (bool)_obj.GetValue("requires_attunement");
        DefaultEquipped = (bool)_obj.GetValue("default_equipped");
        ArmorCategory = (string)_obj.GetValue("armor_category");
        ArmorBaseAc = (int)_obj.GetValue("armor_base_ac");
        AcBonus = (int)_obj.GetValue("ac_bonus");
        MaxDexBonus = (int)_obj.GetValue("max_dex_bonus");
        StrengthRequirement = (int)_obj.GetValue("strength_requirement");
        StealthDisadvantage = (bool)_obj.GetValue("stealth_disadvantage");
        WeaponCategory = (string)_obj.GetValue("weapon_category");
        WeaponRangeType = (string)_obj.GetValue("weapon_range_type");
        DamageDice = (string)_obj.GetValue("damage_dice");
        DamageType = (string)_obj.GetValue("damage_type");
        { var __json0 = _obj.GetValue("weapon_properties"); WeaponProperties = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0; __v0 = (string)__e0; WeaponProperties.Add(__v0); } }
        NormalRange = (int)_obj.GetValue("normal_range");
        LongRange = (int)_obj.GetValue("long_range");
        TwoHandDamageDice = (string)_obj.GetValue("two_hand_damage_dice");
        ToolCategory = (string)_obj.GetValue("tool_category");
        Consumable = (bool)_obj.GetValue("consumable");
        Charges = (int)_obj.GetValue("charges");
        ConsumeOnUse = (bool)_obj.GetValue("consume_on_use");
        { var __json1 = _obj.GetValue("effect_ids"); EffectIds = new System.Collections.Generic.List<string>((__json1 as JArray).Count); foreach(JToken __e1 in __json1) { string __v1; __v1 = (string)__e1; EffectIds.Add(__v1); } }
        EffectApplyCondition = (string)_obj.GetValue("effect_apply_condition");
    }

    public static DndItemDefine DeserializeDndItemDefine(JToken _buf)
    {
        return new dnd.DndItemDefine(_buf);
    }

    public readonly string ItemId;
    public readonly string PackageId;
    public readonly string Name;
    public readonly string ItemType;
    public readonly string Rarity;
    public readonly string Description;
    public readonly string SourceBook;
    public readonly string SourcePage;
    public readonly bool Stackable;
    public readonly int MaxStack;
    public readonly float Weight;
    public readonly int PriceGp;
    public readonly bool IsEquippable;
    public readonly int DefaultQuantity;
    public readonly string EquipmentSlot;
    public readonly bool RequiresAttunement;
    public readonly bool DefaultEquipped;
    public readonly string ArmorCategory;
    public readonly int ArmorBaseAc;
    public readonly int AcBonus;
    public readonly int MaxDexBonus;
    public readonly int StrengthRequirement;
    public readonly bool StealthDisadvantage;
    public readonly string WeaponCategory;
    public readonly string WeaponRangeType;
    public readonly string DamageDice;
    public readonly string DamageType;
    public readonly System.Collections.Generic.List<string> WeaponProperties;
    public readonly int NormalRange;
    public readonly int LongRange;
    public readonly string TwoHandDamageDice;
    public readonly string ToolCategory;
    public readonly bool Consumable;
    public readonly int Charges;
    public readonly bool ConsumeOnUse;
    public readonly System.Collections.Generic.List<string> EffectIds;
    public readonly string EffectApplyCondition;

    public const int __ID__ = -1198945517;
    public override int GetTypeId() => __ID__;

    public void ResolveRef(Tables tables)
    {
    }
}
}
