
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class DndLanguageDefine : Luban.BeanBase
{
    public DndLanguageDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        LanguageId = (string)_obj.GetValue("language_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        EnglishName = (string)_obj.GetValue("english_name");
        LanguageCategory = (string)_obj.GetValue("language_category");
        Description = (string)_obj.GetValue("description");
    }

    public static DndLanguageDefine DeserializeDndLanguageDefine(JToken _buf)
    {
        return new dnd.DndLanguageDefine(_buf);
    }

    /// <summary>
    /// 语言唯一ID。
    /// </summary>
    public readonly string LanguageId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 语言显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 英文名称。
    /// </summary>
    public readonly string EnglishName;
    /// <summary>
    /// standard/exotic。
    /// </summary>
    public readonly string LanguageCategory;
    /// <summary>
    /// 说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = 723314425;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "languageId:" + LanguageId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "englishName:" + EnglishName + ","
        + "languageCategory:" + LanguageCategory + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

