
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class DndToolDefine : Luban.BeanBase
{
    public DndToolDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ToolId = (string)_obj.GetValue("tool_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        ToolCategory = (string)_obj.GetValue("tool_category");
        EnglishName = (string)_obj.GetValue("english_name");
        PriceGp = (float)_obj.GetValue("price_gp");
        Weight = (float)_obj.GetValue("weight");
        SourceBook = (string)_obj.GetValue("source_book");
        SourcePage = (string)_obj.GetValue("source_page");
        Description = (string)_obj.GetValue("description");
    }

    public static DndToolDefine DeserializeDndToolDefine(JToken _buf)
    {
        return new dnd.DndToolDefine(_buf);
    }

    public readonly string ToolId;
    public readonly string PackageId;
    public readonly string Name;
    public readonly string ToolCategory;
    public readonly string EnglishName;
    public readonly float PriceGp;
    public readonly float Weight;
    public readonly string SourceBook;
    public readonly string SourcePage;
    public readonly string Description;


    public const int __ID__ = 945938489;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "toolId:" + ToolId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "toolCategory:" + ToolCategory + ","
        + "englishName:" + EnglishName + ","
        + "priceGp:" + PriceGp + ","
        + "weight:" + Weight + ","
        + "sourceBook:" + SourceBook + ","
        + "sourcePage:" + SourcePage + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

