
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class EnumList : Luban.BeanBase
{
    public EnumList(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        EnumType = (string)_obj.GetValue("enum_type");
        Value = (string)_obj.GetValue("value");
        Description = (string)_obj.GetValue("description");
    }

    public static EnumList DeserializeEnumList(JToken _buf)
    {
        return new dnd.EnumList(_buf);
    }

    /// <summary>
    /// 枚举类别。
    /// </summary>
    public readonly string EnumType;
    /// <summary>
    /// 枚举值。
    /// </summary>
    public readonly string Value;
    /// <summary>
    /// 说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -1794162765;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enumType:" + EnumType + ","
        + "value:" + Value + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

