
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class EnumList : Luban.BeanBase
{
    public EnumList(ByteBuf _buf) 
    {
        EnumType = _buf.ReadString();
        Value = _buf.ReadString();
        Description = _buf.ReadString();
    }

    public static EnumList DeserializeEnumList(ByteBuf _buf)
    {
        return new dnd.EnumList(_buf);
    }

    /// <summary>
    /// 枚举类别。
    /// </summary>
    public readonly string EnumType;
    /// <summary>
    /// 枚举值。
    /// </summary>
    public readonly string Value;
    /// <summary>
    /// 说明。
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -1794162765;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "enumType:" + EnumType + ","
        + "value:" + Value + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

