
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class FeatureDefine : Luban.BeanBase
{
    public FeatureDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        FeatureId = (string)_obj.GetValue("feature_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        FeatureType = (string)_obj.GetValue("feature_type");
        SourceRef = (string)_obj.GetValue("source_ref");
        { var __json0 = _obj.GetValue("prerequisite_ids"); PrerequisiteIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  PrerequisiteIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("effect_ids"); EffectIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  EffectIds.Add(__v0); }   }
        Description = (string)_obj.GetValue("description");
    }

    public static FeatureDefine DeserializeFeatureDefine(JToken _buf)
    {
        return new dnd.FeatureDefine(_buf);
    }

    /// <summary>
    /// 特性唯一ID。职业、种族、背景、专长都可以引用。
    /// </summary>
    public readonly string FeatureId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 特性显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Class / Race / Background / Feat / Spell / Custom。
    /// </summary>
    public readonly string FeatureType;
    /// <summary>
    /// 来源引用，例如 custom_class:2。
    /// </summary>
    public readonly string SourceRef;
    /// <summary>
    /// 前置条件ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> PrerequisiteIds;
    /// <summary>
    /// 关联 TbFeatureEffect.effect_id 列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> EffectIds;
    /// <summary>
    /// 用户手动录入的描述文本。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -644109731;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "featureId:" + FeatureId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "featureType:" + FeatureType + ","
        + "sourceRef:" + SourceRef + ","
        + "prerequisiteIds:" + Luban.StringUtil.CollectionToString(PrerequisiteIds) + ","
        + "effectIds:" + Luban.StringUtil.CollectionToString(EffectIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

