
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class FeatDefine : Luban.BeanBase
{
    public FeatDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        FeatId = (string)_obj.GetValue("feat_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        { var __json0 = _obj.GetValue("prerequisite_ids"); PrerequisiteIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  PrerequisiteIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("feature_ids"); FeatureIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  FeatureIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("effect_ids"); EffectIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  EffectIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("choice_group_ids"); ChoiceGroupIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ChoiceGroupIds.Add(__v0); }   }
        Description = (string)_obj.GetValue("description");
    }

    public static FeatDefine DeserializeFeatDefine(JToken _buf)
    {
        return new dnd.FeatDefine(_buf);
    }

    /// <summary>
    /// 专长唯一ID。
    /// </summary>
    public readonly string FeatId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 前置条件列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> PrerequisiteIds;
    /// <summary>
    /// 选择该专长后授予的特性。
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeatureIds;
    /// <summary>
    /// 选择该专长后直接授予的效果。
    /// </summary>
    public readonly System.Collections.Generic.List<string> EffectIds;
    /// <summary>
    /// 选择该专长后产生的二级选择。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ChoiceGroupIds;
    /// <summary>
    /// 用户录入说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -1829855487;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "featId:" + FeatId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "prerequisiteIds:" + Luban.StringUtil.CollectionToString(PrerequisiteIds) + ","
        + "featureIds:" + Luban.StringUtil.CollectionToString(FeatureIds) + ","
        + "effectIds:" + Luban.StringUtil.CollectionToString(EffectIds) + ","
        + "choiceGroupIds:" + Luban.StringUtil.CollectionToString(ChoiceGroupIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

