
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class LevelExperience : Luban.BeanBase
{
    public LevelExperience(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Level = (int)_obj.GetValue("level");
        ExperienceThreshold = (int)_obj.GetValue("experience_threshold");
        ProficiencyBonus = (int)_obj.GetValue("proficiency_bonus");
        Description = (string)_obj.GetValue("description");
    }

    public static LevelExperience DeserializeLevelExperience(JToken _buf)
    {
        return new dnd.LevelExperience(_buf);
    }

    /// <summary>
    /// 角色等级，范围1-20。
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 达到该等级所需的累计经验值。
    /// </summary>
    public readonly int ExperienceThreshold;
    /// <summary>
    /// 该等级对应的熟练加值。
    /// </summary>
    public readonly int ProficiencyBonus;
    /// <summary>
    /// 备注。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -585047270;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "level:" + Level + ","
        + "experienceThreshold:" + ExperienceThreshold + ","
        + "proficiencyBonus:" + ProficiencyBonus + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

