
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class RaceMainDefine : Luban.BeanBase
{
    public RaceMainDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        MainRaceId = (string)_obj.GetValue("main_race_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        Size = (string)_obj.GetValue("size");
        Speed = (int)_obj.GetValue("speed");
        { var __json0 = _obj.GetValue("language_ids"); LanguageIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  LanguageIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("main_feature_ids"); MainFeatureIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  MainFeatureIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("choice_group_ids"); ChoiceGroupIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ChoiceGroupIds.Add(__v0); }   }
        Description = (string)_obj.GetValue("description");
    }

    public static RaceMainDefine DeserializeRaceMainDefine(JToken _buf)
    {
        return new dnd.RaceMainDefine(_buf);
    }

    /// <summary>
    /// 主要种族唯一ID。
    /// </summary>
    public readonly string MainRaceId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 主要种族显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 体型。
    /// </summary>
    public readonly string Size;
    /// <summary>
    /// 基础速度。
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 语言ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> LanguageIds;
    /// <summary>
    /// 主要种族自身特性。若该种族存在亚种且该行只承担父层结构，则此列留空。
    /// </summary>
    public readonly System.Collections.Generic.List<string> MainFeatureIds;
    /// <summary>
    /// 主要种族层需要选择的内容。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ChoiceGroupIds;
    /// <summary>
    /// 说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -1659520519;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "mainRaceId:" + MainRaceId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "size:" + Size + ","
        + "speed:" + Speed + ","
        + "languageIds:" + Luban.StringUtil.CollectionToString(LanguageIds) + ","
        + "mainFeatureIds:" + Luban.StringUtil.CollectionToString(MainFeatureIds) + ","
        + "choiceGroupIds:" + Luban.StringUtil.CollectionToString(ChoiceGroupIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

