
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class RaceDefine : Luban.BeanBase
{
    public RaceDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        RaceId = (string)_obj.GetValue("race_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        Size = (string)_obj.GetValue("size");
        Speed = (int)_obj.GetValue("speed");
        { var __json0 = _obj.GetValue("language_ids"); LanguageIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  LanguageIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("feature_ids"); FeatureIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  FeatureIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("choice_group_ids"); ChoiceGroupIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ChoiceGroupIds.Add(__v0); }   }
        Description = (string)_obj.GetValue("description");
    }

    public static RaceDefine DeserializeRaceDefine(JToken _buf)
    {
        return new dnd.RaceDefine(_buf);
    }

    /// <summary>
    /// 种族/血统唯一ID。
    /// </summary>
    public readonly string RaceId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 体型。
    /// </summary>
    public readonly string Size;
    /// <summary>
    /// 基础速度。
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 语言ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> LanguageIds;
    /// <summary>
    /// 自动获得的种族特性。
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeatureIds;
    /// <summary>
    /// 需要选择的内容。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ChoiceGroupIds;
    /// <summary>
    /// 用户录入说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = 1804800352;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "raceId:" + RaceId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "size:" + Size + ","
        + "speed:" + Speed + ","
        + "languageIds:" + Luban.StringUtil.CollectionToString(LanguageIds) + ","
        + "featureIds:" + Luban.StringUtil.CollectionToString(FeatureIds) + ","
        + "choiceGroupIds:" + Luban.StringUtil.CollectionToString(ChoiceGroupIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

