
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class RaceSubDefine : Luban.BeanBase
{
    public RaceSubDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        SubRaceId = (string)_obj.GetValue("sub_race_id");
        PackageId = (string)_obj.GetValue("package_id");
        MainRaceId = (string)_obj.GetValue("main_race_id");
        Name = (string)_obj.GetValue("name");
        Size = (string)_obj.GetValue("size");
        Speed = (int)_obj.GetValue("speed");
        { var __json0 = _obj.GetValue("unique_feature_ids"); UniqueFeatureIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  UniqueFeatureIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("choice_group_ids"); ChoiceGroupIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ChoiceGroupIds.Add(__v0); }   }
        Description = (string)_obj.GetValue("description");
    }

    public static RaceSubDefine DeserializeRaceSubDefine(JToken _buf)
    {
        return new dnd.RaceSubDefine(_buf);
    }

    /// <summary>
    /// 亚种唯一ID。
    /// </summary>
    public readonly string SubRaceId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 所属主要种族ID。
    /// </summary>
    public readonly string MainRaceId;
    /// <summary>
    /// 亚种显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 体型。
    /// </summary>
    public readonly string Size;
    /// <summary>
    /// 基础速度。
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 亚种独有特性。
    /// </summary>
    public readonly System.Collections.Generic.List<string> UniqueFeatureIds;
    /// <summary>
    /// 亚种层需要选择的内容。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ChoiceGroupIds;
    /// <summary>
    /// 说明。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -1437647274;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "subRaceId:" + SubRaceId + ","
        + "packageId:" + PackageId + ","
        + "mainRaceId:" + MainRaceId + ","
        + "name:" + Name + ","
        + "size:" + Size + ","
        + "speed:" + Speed + ","
        + "uniqueFeatureIds:" + Luban.StringUtil.CollectionToString(UniqueFeatureIds) + ","
        + "choiceGroupIds:" + Luban.StringUtil.CollectionToString(ChoiceGroupIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

