
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class RaceDefine : Luban.BeanBase
{
    public RaceDefine(ByteBuf _buf) 
    {
        RaceId = _buf.ReadString();
        PackageId = _buf.ReadString();
        Name = _buf.ReadString();
        Size = _buf.ReadString();
        Speed = _buf.ReadInt();
        {int n0 = _buf.ReadSize(); LanguageIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); LanguageIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); FeatureIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); FeatureIds.Add(_e0);}}
        {int n0 = _buf.ReadSize(); ChoiceGroupIds = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); ChoiceGroupIds.Add(_e0);}}
        Description = _buf.ReadString();
    }

    public static RaceDefine DeserializeRaceDefine(ByteBuf _buf)
    {
        return new dnd.RaceDefine(_buf);
    }

    /// <summary>
    /// 种族/血统唯一ID。
    /// </summary>
    public readonly string RaceId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 显示名称。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 体型。
    /// </summary>
    public readonly string Size;
    /// <summary>
    /// 基础速度。
    /// </summary>
    public readonly int Speed;
    /// <summary>
    /// 语言ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> LanguageIds;
    /// <summary>
    /// 自动获得的种族特性。
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeatureIds;
    /// <summary>
    /// 需要选择的内容。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ChoiceGroupIds;
    /// <summary>
    /// 用户录入说明。
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = 1804800352;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "raceId:" + RaceId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "size:" + Size + ","
        + "speed:" + Speed + ","
        + "languageIds:" + Luban.StringUtil.CollectionToString(LanguageIds) + ","
        + "featureIds:" + Luban.StringUtil.CollectionToString(FeatureIds) + ","
        + "choiceGroupIds:" + Luban.StringUtil.CollectionToString(ChoiceGroupIds) + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

