
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class RulePackage : Luban.BeanBase
{
    public RulePackage(ByteBuf _buf) 
    {
        PackageId = _buf.ReadString();
        PackageName = _buf.ReadString();
        Version = _buf.ReadString();
        Author = _buf.ReadString();
        License = _buf.ReadString();
        Description = _buf.ReadString();
    }

    public static RulePackage DeserializeRulePackage(ByteBuf _buf)
    {
        return new dnd.RulePackage(_buf);
    }

    /// <summary>
    /// 规则包唯一ID。建议小写蛇形命名。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 规则包显示名称。
    /// </summary>
    public readonly string PackageName;
    /// <summary>
    /// 版本号。
    /// </summary>
    public readonly string Version;
    /// <summary>
    /// 作者/维护者。
    /// </summary>
    public readonly string Author;
    /// <summary>
    /// 授权说明，例如 UserProvided / CC-BY-4.0 / Private。
    /// </summary>
    public readonly string License;
    /// <summary>
    /// 规则包说明。
    /// </summary>
    public readonly string Description;
   
    public const int __ID__ = -960385354;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "packageId:" + PackageId + ","
        + "packageName:" + PackageName + ","
        + "version:" + Version + ","
        + "author:" + Author + ","
        + "license:" + License + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

