
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class SkillDefine : Luban.BeanBase
{
    public SkillDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        SkillId = (string)_obj.GetValue("skill_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        AbilityId = (string)_obj.GetValue("ability_id");
        Description = (string)_obj.GetValue("description");
    }

    public static SkillDefine DeserializeSkillDefine(JToken _buf)
    {
        return new dnd.SkillDefine(_buf);
    }

    /// <summary>
    /// 亚种唯一ID。
    /// </summary>
    public readonly string SkillId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 所属主要种族ID。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 亚种显示名称。
    /// </summary>
    public readonly string AbilityId;
    /// <summary>
    /// 体型。
    /// </summary>
    public readonly string Description;


    public const int __ID__ = -2098275208;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "skillId:" + SkillId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "abilityId:" + AbilityId + ","
        + "description:" + Description + ","
        + "}";
    }
}
}

