
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class SpellSlotProgression : Luban.BeanBase
{
    public SpellSlotProgression(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        ProgressionId = (string)_obj.GetValue("progression_id");
        ProgressionLevel = (int)_obj.GetValue("progression_level");
        MaxSpellLevel = (int)_obj.GetValue("max_spell_level");
        Slot1 = (int)_obj.GetValue("slot_1");
        Slot2 = (int)_obj.GetValue("slot_2");
        Slot3 = (int)_obj.GetValue("slot_3");
        Slot4 = (int)_obj.GetValue("slot_4");
        Slot5 = (int)_obj.GetValue("slot_5");
        Slot6 = (int)_obj.GetValue("slot_6");
        Slot7 = (int)_obj.GetValue("slot_7");
        Slot8 = (int)_obj.GetValue("slot_8");
        Slot9 = (int)_obj.GetValue("slot_9");
    }

    public static SpellSlotProgression DeserializeSpellSlotProgression(JToken _buf)
    {
        return new dnd.SpellSlotProgression(_buf);
    }

    /// <summary>
    /// Spell slot progression id.
    /// </summary>
    public readonly string ProgressionId;
    /// <summary>
    /// Progression level, usually class level.
    /// </summary>
    public readonly int ProgressionLevel;
    /// <summary>
    /// Highest spell level available at this progression level.
    /// </summary>
    public readonly int MaxSpellLevel;
    /// <summary>
    /// Level 1 spell slots.
    /// </summary>
    public readonly int Slot1;
    /// <summary>
    /// Level 2 spell slots.
    /// </summary>
    public readonly int Slot2;
    /// <summary>
    /// Level 3 spell slots.
    /// </summary>
    public readonly int Slot3;
    /// <summary>
    /// Level 4 spell slots.
    /// </summary>
    public readonly int Slot4;
    /// <summary>
    /// Level 5 spell slots.
    /// </summary>
    public readonly int Slot5;
    /// <summary>
    /// Level 6 spell slots.
    /// </summary>
    public readonly int Slot6;
    /// <summary>
    /// Level 7 spell slots.
    /// </summary>
    public readonly int Slot7;
    /// <summary>
    /// Level 8 spell slots.
    /// </summary>
    public readonly int Slot8;
    /// <summary>
    /// Level 9 spell slots.
    /// </summary>
    public readonly int Slot9;


    public const int __ID__ = -297246711;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "progressionId:" + ProgressionId + ","
        + "progressionLevel:" + ProgressionLevel + ","
        + "maxSpellLevel:" + MaxSpellLevel + ","
        + "slot1:" + Slot1 + ","
        + "slot2:" + Slot2 + ","
        + "slot3:" + Slot3 + ","
        + "slot4:" + Slot4 + ","
        + "slot5:" + Slot5 + ","
        + "slot6:" + Slot6 + ","
        + "slot7:" + Slot7 + ","
        + "slot8:" + Slot8 + ","
        + "slot9:" + Slot9 + ","
        + "}";
    }
}
}

