
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
public sealed partial class SpellDefine : Luban.BeanBase
{
    public SpellDefine(ByteBuf _buf) 
    {
        SpellId = _buf.ReadString();
        PackageId = _buf.ReadString();
        Name = _buf.ReadString();
        Level = _buf.ReadInt();
        School = _buf.ReadString();
        CastingTime = _buf.ReadString();
        Range = _buf.ReadString();
        {int n0 = _buf.ReadSize(); Components = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); Components.Add(_e0);}}
        Duration = _buf.ReadString();
        Concentration = _buf.ReadBool();
        Ritual = _buf.ReadBool();
        AttackType = _buf.ReadString();
        SaveAbility = _buf.ReadString();
        DamageFormula = _buf.ReadString();
        DamageType = _buf.ReadString();
        {int n0 = _buf.ReadSize(); EffectTags = new System.Collections.Generic.List<string>(n0);for(var i0 = 0 ; i0 < n0 ; i0++) { string _e0;  _e0 = _buf.ReadString(); EffectTags.Add(_e0);}}
        Description = _buf.ReadString();
        HigherLevelDescription = _buf.ReadString();
    }

    public static SpellDefine DeserializeSpellDefine(ByteBuf _buf)
    {
        return new dnd.SpellDefine(_buf);
    }

    /// <summary>
    /// 法术唯一ID。
    /// </summary>
    public readonly string SpellId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 法术名称，由用户手动录入。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 法术环级，0表示戏法。
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 法术学派。
    /// </summary>
    public readonly string School;
    /// <summary>
    /// 施法时间。
    /// </summary>
    public readonly string CastingTime;
    /// <summary>
    /// 距离。
    /// </summary>
    public readonly string Range;
    /// <summary>
    /// 成分，例如 V;S;M。
    /// </summary>
    public readonly System.Collections.Generic.List<string> Components;
    /// <summary>
    /// 持续时间。
    /// </summary>
    public readonly string Duration;
    /// <summary>
    /// 是否专注。
    /// </summary>
    public readonly bool Concentration;
    /// <summary>
    /// 是否仪式。
    /// </summary>
    public readonly bool Ritual;
    /// <summary>
    /// None / SpellAttack / Save / Utility。
    /// </summary>
    public readonly string AttackType;
    /// <summary>
    /// 豁免属性。
    /// </summary>
    public readonly string SaveAbility;
    /// <summary>
    /// 伤害公式，例如1d8。第一版可仅展示。
    /// </summary>
    public readonly string DamageFormula;
    /// <summary>
    /// 伤害类型。
    /// </summary>
    public readonly string DamageType;
    /// <summary>
    /// 标签列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> EffectTags;
    /// <summary>
    /// 用户录入的法术描述。
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 升环描述。
    /// </summary>
    public readonly string HigherLevelDescription;
   
    public const int __ID__ = -145992177;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "spellId:" + SpellId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "level:" + Level + ","
        + "school:" + School + ","
        + "castingTime:" + CastingTime + ","
        + "range:" + Range + ","
        + "components:" + Luban.StringUtil.CollectionToString(Components) + ","
        + "duration:" + Duration + ","
        + "concentration:" + Concentration + ","
        + "ritual:" + Ritual + ","
        + "attackType:" + AttackType + ","
        + "saveAbility:" + SaveAbility + ","
        + "damageFormula:" + DamageFormula + ","
        + "damageType:" + DamageType + ","
        + "effectTags:" + Luban.StringUtil.CollectionToString(EffectTags) + ","
        + "description:" + Description + ","
        + "higherLevelDescription:" + HigherLevelDescription + ","
        + "}";
    }
}
}

