
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class SpellDefine : Luban.BeanBase
{
    public SpellDefine(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        SpellId = (string)_obj.GetValue("spell_id");
        PackageId = (string)_obj.GetValue("package_id");
        Name = (string)_obj.GetValue("name");
        Level = (int)_obj.GetValue("level");
        School = (string)_obj.GetValue("school");
        CastingTime = (string)_obj.GetValue("casting_time");
        Range = (string)_obj.GetValue("range");
        { var __json0 = _obj.GetValue("components"); Components = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  Components.Add(__v0); }   }
        Duration = (string)_obj.GetValue("duration");
        Concentration = (bool)_obj.GetValue("concentration");
        Ritual = (bool)_obj.GetValue("ritual");
        AttackType = (string)_obj.GetValue("attack_type");
        SaveAbility = (string)_obj.GetValue("save_ability");
        DamageFormula = (string)_obj.GetValue("damage_formula");
        DamageType = (string)_obj.GetValue("damage_type");
        { var __json0 = _obj.GetValue("effect_tags"); EffectTags = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  EffectTags.Add(__v0); }   }
        Description = (string)_obj.GetValue("description");
        HigherLevelDescription = (string)_obj.GetValue("higher_level_description");
    }

    public static SpellDefine DeserializeSpellDefine(JToken _buf)
    {
        return new dnd.SpellDefine(_buf);
    }

    /// <summary>
    /// 法术唯一ID。
    /// </summary>
    public readonly string SpellId;
    /// <summary>
    /// 来源规则包ID。
    /// </summary>
    public readonly string PackageId;
    /// <summary>
    /// 法术名称，由用户手动录入。
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 法术环级，0表示戏法。
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 法术学派。
    /// </summary>
    public readonly string School;
    /// <summary>
    /// 施法时间。
    /// </summary>
    public readonly string CastingTime;
    /// <summary>
    /// 距离。
    /// </summary>
    public readonly string Range;
    /// <summary>
    /// 成分，例如 V;S;M。
    /// </summary>
    public readonly System.Collections.Generic.List<string> Components;
    /// <summary>
    /// 持续时间。
    /// </summary>
    public readonly string Duration;
    /// <summary>
    /// 是否专注。
    /// </summary>
    public readonly bool Concentration;
    /// <summary>
    /// 是否仪式。
    /// </summary>
    public readonly bool Ritual;
    /// <summary>
    /// None / SpellAttack / Save / Utility。
    /// </summary>
    public readonly string AttackType;
    /// <summary>
    /// 豁免属性。
    /// </summary>
    public readonly string SaveAbility;
    /// <summary>
    /// 伤害公式，例如1d8。第一版可仅展示。
    /// </summary>
    public readonly string DamageFormula;
    /// <summary>
    /// 伤害类型。
    /// </summary>
    public readonly string DamageType;
    /// <summary>
    /// 标签列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> EffectTags;
    /// <summary>
    /// 用户录入的法术描述。
    /// </summary>
    public readonly string Description;
    /// <summary>
    /// 升环描述。
    /// </summary>
    public readonly string HigherLevelDescription;


    public const int __ID__ = -145992177;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "spellId:" + SpellId + ","
        + "packageId:" + PackageId + ","
        + "name:" + Name + ","
        + "level:" + Level + ","
        + "school:" + School + ","
        + "castingTime:" + CastingTime + ","
        + "range:" + Range + ","
        + "components:" + Luban.StringUtil.CollectionToString(Components) + ","
        + "duration:" + Duration + ","
        + "concentration:" + Concentration + ","
        + "ritual:" + Ritual + ","
        + "attackType:" + AttackType + ","
        + "saveAbility:" + SaveAbility + ","
        + "damageFormula:" + DamageFormula + ","
        + "damageType:" + DamageType + ","
        + "effectTags:" + Luban.StringUtil.CollectionToString(EffectTags) + ","
        + "description:" + Description + ","
        + "higherLevelDescription:" + HigherLevelDescription + ","
        + "}";
    }
}
}

