
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class SubclassLevelProgression : Luban.BeanBase
{
    public SubclassLevelProgression(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        SubclassId = (string)_obj.GetValue("subclass_id");
        ClassId = (string)_obj.GetValue("class_id");
        Level = (int)_obj.GetValue("level");
        { var __json0 = _obj.GetValue("feature_ids"); FeatureIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  FeatureIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("choice_group_ids"); ChoiceGroupIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ChoiceGroupIds.Add(__v0); }   }
        { var __json0 = _obj.GetValue("resource_grant_ids"); ResourceGrantIds = new System.Collections.Generic.List<string>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { string __v0;  __v0 = (string)__e0;  ResourceGrantIds.Add(__v0); }   }
        {if (_obj.TryGetValue("spell_slot_progression_level", out var _j)) { SpellSlotProgressionLevel = (int)_j; } else { SpellSlotProgressionLevel = null; } }
        {if (_obj.TryGetValue("cantrip_known", out var _j)) { CantripKnown = (int)_j; } else { CantripKnown = null; } }
        {if (_obj.TryGetValue("spell_known", out var _j)) { SpellKnown = (int)_j; } else { SpellKnown = null; } }
        PreparedSpellFormula = (string)_obj.GetValue("prepared_spell_formula");
        Note = (string)_obj.GetValue("note");
    }

    public static SubclassLevelProgression DeserializeSubclassLevelProgression(JToken _buf)
    {
        return new dnd.SubclassLevelProgression(_buf);
    }

    /// <summary>
    /// 子职业ID，引用 TbChoiceOption.option_id。
    /// </summary>
    public readonly string SubclassId;
    /// <summary>
    /// 所属主职业ID。
    /// </summary>
    public readonly string ClassId;
    /// <summary>
    /// 获得该子职业进阶内容时的主职业等级。
    /// </summary>
    public readonly int Level;
    /// <summary>
    /// 该等级获得的子职业特性ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> FeatureIds;
    /// <summary>
    /// 该等级需要进行的子职业内选择。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ChoiceGroupIds;
    /// <summary>
    /// 该等级授予或刷新资源的ID列表。
    /// </summary>
    public readonly System.Collections.Generic.List<string> ResourceGrantIds;
    /// <summary>
    /// 子职业施法进度等级。
    /// </summary>
    public readonly int? SpellSlotProgressionLevel;
    /// <summary>
    /// 该等级已知戏法数量。
    /// </summary>
    public readonly int? CantripKnown;
    /// <summary>
    /// 该等级已知法术数量。
    /// </summary>
    public readonly int? SpellKnown;
    /// <summary>
    /// 准备法术数量公式。
    /// </summary>
    public readonly string PreparedSpellFormula;
    /// <summary>
    /// 备注。
    /// </summary>
    public readonly string Note;


    public const int __ID__ = -573003165;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "subclassId:" + SubclassId + ","
        + "classId:" + ClassId + ","
        + "level:" + Level + ","
        + "featureIds:" + Luban.StringUtil.CollectionToString(FeatureIds) + ","
        + "choiceGroupIds:" + Luban.StringUtil.CollectionToString(ChoiceGroupIds) + ","
        + "resourceGrantIds:" + Luban.StringUtil.CollectionToString(ResourceGrantIds) + ","
        + "spellSlotProgressionLevel:" + SpellSlotProgressionLevel + ","
        + "cantripKnown:" + CantripKnown + ","
        + "spellKnown:" + SpellKnown + ","
        + "preparedSpellFormula:" + PreparedSpellFormula + ","
        + "note:" + Note + ","
        + "}";
    }
}
}

