
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 阵营定义表
/// </summary>
public partial class TbAlignment
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.Alignment> _dataMap;
    private readonly System.Collections.Generic.List<dnd.Alignment> _dataList;
    
    public TbAlignment(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.Alignment>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.Alignment>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.Alignment _v;
            _v = global::GameConfig.dnd.Alignment.DeserializeAlignment(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.AlignmentId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.Alignment> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.Alignment> DataList => _dataList;

    public dnd.Alignment GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.Alignment Get(string key) => _dataMap[key];
    public dnd.Alignment this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

