
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
/// <summary>
/// 角色创建与升级选择组表
/// </summary>
public partial class TbChoiceGroup
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.ChoiceGroup> _dataMap;
    private readonly System.Collections.Generic.List<dnd.ChoiceGroup> _dataList;
    
    public TbChoiceGroup(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.ChoiceGroup>(n);
        _dataList = new System.Collections.Generic.List<dnd.ChoiceGroup>(n);
        for(int i = n ; i > 0 ; --i)
        {
            dnd.ChoiceGroup _v;
            _v = global::GameConfig.dnd.ChoiceGroup.DeserializeChoiceGroup(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.ChoiceGroupId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.ChoiceGroup> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.ChoiceGroup> DataList => _dataList;

    public dnd.ChoiceGroup GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.ChoiceGroup Get(string key) => _dataMap[key];
    public dnd.ChoiceGroup this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

