
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 职业定义表
/// </summary>
public partial class TbClassDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.ClassDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.ClassDefine> _dataList;
    
    public TbClassDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.ClassDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.ClassDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.ClassDefine _v;
            _v = global::GameConfig.dnd.ClassDefine.DeserializeClassDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ClassId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.ClassDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.ClassDefine> DataList => _dataList;

    public dnd.ClassDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.ClassDefine Get(string key) => _dataMap[key];
    public dnd.ClassDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

