
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
/// <summary>
/// 职业1-20级成长表。业务层按 class_id + level 查询。
/// </summary>
public partial class TbClassLevelProgression
{
    private readonly System.Collections.Generic.List<dnd.ClassLevelProgression> _dataList;


    public TbClassLevelProgression(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataList = new System.Collections.Generic.List<dnd.ClassLevelProgression>(n);
        for(int i = n ; i > 0 ; --i)
        {
            dnd.ClassLevelProgression _v;
            _v = global::GameConfig.dnd.ClassLevelProgression.DeserializeClassLevelProgression(_buf);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<dnd.ClassLevelProgression> DataList => _dataList;

    
    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}

}

