
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// DnD 语言定义表
/// </summary>
public partial class TbDndLanguageDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.DndLanguageDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.DndLanguageDefine> _dataList;
    
    public TbDndLanguageDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.DndLanguageDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.DndLanguageDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.DndLanguageDefine _v;
            _v = global::GameConfig.dnd.DndLanguageDefine.DeserializeDndLanguageDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.LanguageId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.DndLanguageDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.DndLanguageDefine> DataList => _dataList;

    public dnd.DndLanguageDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.DndLanguageDefine Get(string key) => _dataMap[key];
    public dnd.DndLanguageDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

