
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// DnD 工具定义表
/// </summary>
public partial class TbDndToolDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.DndToolDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.DndToolDefine> _dataList;
    
    public TbDndToolDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.DndToolDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.DndToolDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.DndToolDefine _v;
            _v = global::GameConfig.dnd.DndToolDefine.DeserializeDndToolDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ToolId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.DndToolDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.DndToolDefine> DataList => _dataList;

    public dnd.DndToolDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.DndToolDefine Get(string key) => _dataMap[key];
    public dnd.DndToolDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

