
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// DnD 物品类型定义表。用于物品编辑默认行为、背包堆叠与使用逻辑。
/// </summary>
public partial class TbDndItemTypeDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.DndItemTypeDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.DndItemTypeDefine> _dataList;
    
    public TbDndItemTypeDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.DndItemTypeDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.DndItemTypeDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.DndItemTypeDefine _v;
            _v = global::GameConfig.dnd.DndItemTypeDefine.DeserializeDndItemTypeDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemTypeId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.DndItemTypeDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.DndItemTypeDefine> DataList => _dataList;

    public dnd.DndItemTypeDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.DndItemTypeDefine Get(string key) => _dataMap[key];
    public dnd.DndItemTypeDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

