
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;

namespace GameConfig.dnd
{
/// <summary>
/// DnD item definition table.
/// </summary>
public partial class TbDndItemDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.DndItemDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.DndItemDefine> _dataList;

    public TbDndItemDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.DndItemDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.DndItemDefine>(_buf.Count);

        foreach(JObject _ele in _buf)
        {
            dnd.DndItemDefine _v;
            _v = global::GameConfig.dnd.DndItemDefine.DeserializeDndItemDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.ItemId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.DndItemDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.DndItemDefine> DataList => _dataList;

    public dnd.DndItemDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.DndItemDefine Get(string key) => _dataMap[key];
    public dnd.DndItemDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}
