
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 外部枚举/字典值表。业务层按 enum_type + value 查询。
/// </summary>
public partial class TbEnumList
{
    private readonly System.Collections.Generic.List<dnd.EnumList> _dataList;



    public TbEnumList(JArray _buf)
    {
        _dataList = new System.Collections.Generic.List<dnd.EnumList>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.EnumList _v;
            _v = global::GameConfig.dnd.EnumList.DeserializeEnumList(_ele);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<dnd.EnumList> DataList => _dataList;



    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

