
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
/// <summary>
/// 结构化特性效果表
/// </summary>
public partial class TbFeatureEffect
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.FeatureEffect> _dataMap;
    private readonly System.Collections.Generic.List<dnd.FeatureEffect> _dataList;
    
    public TbFeatureEffect(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.FeatureEffect>(n);
        _dataList = new System.Collections.Generic.List<dnd.FeatureEffect>(n);
        for(int i = n ; i > 0 ; --i)
        {
            dnd.FeatureEffect _v;
            _v = global::GameConfig.dnd.FeatureEffect.DeserializeFeatureEffect(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.EffectId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.FeatureEffect> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.FeatureEffect> DataList => _dataList;

    public dnd.FeatureEffect GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.FeatureEffect Get(string key) => _dataMap[key];
    public dnd.FeatureEffect this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

