
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 专长定义表
/// </summary>
public partial class TbFeatDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.FeatDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.FeatDefine> _dataList;
    
    public TbFeatDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.FeatDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.FeatDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.FeatDefine _v;
            _v = global::GameConfig.dnd.FeatDefine.DeserializeFeatDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.FeatId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.FeatDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.FeatDefine> DataList => _dataList;

    public dnd.FeatDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.FeatDefine Get(string key) => _dataMap[key];
    public dnd.FeatDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

