
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

public partial class TbLevelExperience
{
    private readonly System.Collections.Generic.Dictionary<int, dnd.LevelExperience> _dataMap;
    private readonly System.Collections.Generic.List<dnd.LevelExperience> _dataList;
    
    public TbLevelExperience(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<int, dnd.LevelExperience>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.LevelExperience>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.LevelExperience _v;
            _v = global::GameConfig.dnd.LevelExperience.DeserializeLevelExperience(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.Level, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<int, dnd.LevelExperience> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.LevelExperience> DataList => _dataList;

    public dnd.LevelExperience GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.LevelExperience Get(int key) => _dataMap[key];
    public dnd.LevelExperience this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

