
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 种族/血统定义表
/// </summary>
public partial class TbRaceDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.RaceDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.RaceDefine> _dataList;
    
    public TbRaceDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.RaceDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.RaceDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.RaceDefine _v;
            _v = global::GameConfig.dnd.RaceDefine.DeserializeRaceDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.RaceId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.RaceDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.RaceDefine> DataList => _dataList;

    public dnd.RaceDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.RaceDefine Get(string key) => _dataMap[key];
    public dnd.RaceDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

