
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 主要种族定义表
/// </summary>
public partial class TbRaceMainDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.RaceMainDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.RaceMainDefine> _dataList;
    
    public TbRaceMainDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.RaceMainDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.RaceMainDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.RaceMainDefine _v;
            _v = global::GameConfig.dnd.RaceMainDefine.DeserializeRaceMainDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.MainRaceId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.RaceMainDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.RaceMainDefine> DataList => _dataList;

    public dnd.RaceMainDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.RaceMainDefine Get(string key) => _dataMap[key];
    public dnd.RaceMainDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

