
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 亚种定义表
/// </summary>
public partial class TbRaceSubDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.RaceSubDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.RaceSubDefine> _dataList;
    
    public TbRaceSubDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.RaceSubDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.RaceSubDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.RaceSubDefine _v;
            _v = global::GameConfig.dnd.RaceSubDefine.DeserializeRaceSubDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.SubRaceId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.RaceSubDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.RaceSubDefine> DataList => _dataList;

    public dnd.RaceSubDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.RaceSubDefine Get(string key) => _dataMap[key];
    public dnd.RaceSubDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

