
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 规则包定义表
/// </summary>
public partial class TbRulePackage
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.RulePackage> _dataMap;
    private readonly System.Collections.Generic.List<dnd.RulePackage> _dataList;
    
    public TbRulePackage(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.RulePackage>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.RulePackage>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.RulePackage _v;
            _v = global::GameConfig.dnd.RulePackage.DeserializeRulePackage(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.PackageId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.RulePackage> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.RulePackage> DataList => _dataList;

    public dnd.RulePackage GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.RulePackage Get(string key) => _dataMap[key];
    public dnd.RulePackage this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

