
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 技能定义表。用于技能熟练选择等配置。
/// </summary>
public partial class TbSkillDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.SkillDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.SkillDefine> _dataList;
    
    public TbSkillDefine(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.SkillDefine>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.SkillDefine>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.SkillDefine _v;
            _v = global::GameConfig.dnd.SkillDefine.DeserializeSkillDefine(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.SkillId, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.SkillDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.SkillDefine> DataList => _dataList;

    public dnd.SkillDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.SkillDefine Get(string key) => _dataMap[key];
    public dnd.SkillDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

