
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;


namespace GameConfig.dnd
{
/// <summary>
/// 法术定义表
/// </summary>
public partial class TbSpellDefine
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.SpellDefine> _dataMap;
    private readonly System.Collections.Generic.List<dnd.SpellDefine> _dataList;
    
    public TbSpellDefine(ByteBuf _buf)
    {
        int n = _buf.ReadSize();
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.SpellDefine>(n);
        _dataList = new System.Collections.Generic.List<dnd.SpellDefine>(n);
        for(int i = n ; i > 0 ; --i)
        {
            dnd.SpellDefine _v;
            _v = global::GameConfig.dnd.SpellDefine.DeserializeSpellDefine(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.SpellId, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.SpellDefine> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.SpellDefine> DataList => _dataList;

    public dnd.SpellDefine GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.SpellDefine Get(string key) => _dataMap[key];
    public dnd.SpellDefine this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

