
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// Spell slot progression table.
/// </summary>
public partial class TbSpellSlotProgression
{
    private readonly System.Collections.Generic.List<dnd.SpellSlotProgression> _dataList;



    public TbSpellSlotProgression(JArray _buf)
    {
        _dataList = new System.Collections.Generic.List<dnd.SpellSlotProgression>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.SpellSlotProgression _v;
            _v = global::GameConfig.dnd.SpellSlotProgression.DeserializeSpellSlotProgression(_ele);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<dnd.SpellSlotProgression> DataList => _dataList;



    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

