
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// 子职业按主职业等级成长表。
/// </summary>
public partial class TbSubclassLevelProgression
{
    private readonly System.Collections.Generic.List<dnd.SubclassLevelProgression> _dataList;



    public TbSubclassLevelProgression(JArray _buf)
    {
        _dataList = new System.Collections.Generic.List<dnd.SubclassLevelProgression>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.SubclassLevelProgression _v;
            _v = global::GameConfig.dnd.SubclassLevelProgression.DeserializeSubclassLevelProgression(_ele);
            _dataList.Add(_v);
        }
    }

    public System.Collections.Generic.IReadOnlyList<dnd.SubclassLevelProgression> DataList => _dataList;



    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }
}
}

