
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Newtonsoft.Json.Linq;
using Luban;



namespace GameConfig.dnd
{

/// <summary>
/// DnD text localization table
/// </summary>
public partial class TbTextLocalize
{
    private readonly System.Collections.Generic.Dictionary<string, dnd.TextLocalize> _dataMap;
    private readonly System.Collections.Generic.List<dnd.TextLocalize> _dataList;
    
    public TbTextLocalize(JArray _buf)
    {
        _dataMap = new System.Collections.Generic.Dictionary<string, dnd.TextLocalize>(_buf.Count);
        _dataList = new System.Collections.Generic.List<dnd.TextLocalize>(_buf.Count);
        
        foreach(JObject _ele in _buf)
        {
            dnd.TextLocalize _v;
            _v = global::GameConfig.dnd.TextLocalize.DeserializeTextLocalize(_ele);
            _dataList.Add(_v);
            _dataMap.Add(_v.TextKey, _v);
         }
    }


    public System.Collections.Generic.IReadOnlyDictionary<string, dnd.TextLocalize> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<dnd.TextLocalize> DataList => _dataList;

    public dnd.TextLocalize GetOrDefault(string key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public dnd.TextLocalize Get(string key) => _dataMap[key];
    public dnd.TextLocalize this[string key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}
}

