
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.dnd
{

public sealed partial class TextLocalize : Luban.BeanBase
{
    public TextLocalize(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        TextKey = (string)_obj.GetValue("text_key");
        Language = (string)_obj.GetValue("language");
        Text = (string)_obj.GetValue("text");
        Context = (string)_obj.GetValue("context");
    }

    public static TextLocalize DeserializeTextLocalize(JToken _buf)
    {
        return new dnd.TextLocalize(_buf);
    }

    /// <summary>
    /// Only localization key. Must not contain Chinese.
    /// </summary>
    public readonly string TextKey;
    /// <summary>
    /// Language code, for example zh_CN.
    /// </summary>
    public readonly string Language;
    /// <summary>
    /// Localized display text. This is the only rule table field allowed to contain Chinese.
    /// </summary>
    public readonly string Text;
    /// <summary>
    /// Optional source context.
    /// </summary>
    public readonly string Context;


    public const int __ID__ = 982171338;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "textKey:" + TextKey + ","
        + "language:" + Language + ","
        + "text:" + Text + ","
        + "context:" + Context + ","
        + "}";
    }
}
}

