
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Newtonsoft.Json.Linq;



namespace GameConfig.item
{

public sealed partial class Item : Luban.BeanBase
{
    public Item(JToken _buf) 
    {
        JObject _obj = _buf as JObject;
        Id = (int)_obj.GetValue("id");
        Name = (string)_obj.GetValue("name");
        Desc = (string)_obj.GetValue("desc");
        Price = (int)_obj.GetValue("price");
        UpgradeToItemId = (int)_obj.GetValue("upgrade_to_item_id");
        UpgradeToItemId_Ref = null;
        {if (_obj.TryGetValue("expire_time", out var _j)) { ExpireTime = (long)_j; } else { ExpireTime = null; } }
        BatchUseable = (bool)_obj.GetValue("batch_useable");
        ExchangeStream = global::GameConfig.item.ItemExchange.DeserializeItemExchange(_obj.GetValue("exchange_stream"));
        { var __json0 = _obj.GetValue("exchange_list"); ExchangeList = new System.Collections.Generic.List<item.ItemExchange>((__json0 as JArray).Count); foreach(JToken __e0 in __json0) { item.ItemExchange __v0;  __v0 = global::GameConfig.item.ItemExchange.DeserializeItemExchange(__e0);  ExchangeList.Add(__v0); }   }
        ExchangeColumn = global::GameConfig.item.ItemExchange.DeserializeItemExchange(_obj.GetValue("exchange_column"));
    }

    public static Item DeserializeItem(JToken _buf)
    {
        return new item.Item(_buf);
    }

    /// <summary>
    /// 这是id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名字
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 价格
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// 引用当前表
    /// </summary>
    public readonly int UpgradeToItemId;
    public item.Item UpgradeToItemId_Ref;
    /// <summary>
    /// 过期时间
    /// </summary>
    public readonly long? ExpireTime;
    /// <summary>
    /// 能否批量使用
    /// </summary>
    public readonly bool BatchUseable;
    /// <summary>
    /// 道具兑换配置
    /// </summary>
    public readonly item.ItemExchange ExchangeStream;
    public readonly System.Collections.Generic.List<item.ItemExchange> ExchangeList;
    /// <summary>
    /// 道具兑换配置
    /// </summary>
    public readonly item.ItemExchange ExchangeColumn;


    public const int __ID__ = 2107285806;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
        UpgradeToItemId_Ref = tables.TbItem.GetOrDefault(UpgradeToItemId);
        ExchangeStream?.ResolveRef(tables);
        foreach (var _e in ExchangeList) { _e?.ResolveRef(tables); }
        ExchangeColumn?.ResolveRef(tables);
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "price:" + Price + ","
        + "upgradeToItemId:" + UpgradeToItemId + ","
        + "expireTime:" + ExpireTime + ","
        + "batchUseable:" + BatchUseable + ","
        + "exchangeStream:" + ExchangeStream + ","
        + "exchangeList:" + Luban.StringUtil.CollectionToString(ExchangeList) + ","
        + "exchangeColumn:" + ExchangeColumn + ","
        + "}";
    }
}
}

